### ISSUE TITLE
Write test suite for frontend

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/dashboard#128]

**Comment by erickzhao** [comment]
@pierreTklein how extensive do we want this to be?

**Comment by pierreTklein** [comment]
I would love to have these:
- Test suite to verify that everything compiles when rendered
- We are able to test redirects / page permissions
Nice to have:
- Stub the API endpoints, and test:
    - failure cases of an API call, we do not crash
    - Success cases do the right thing as well

**Comment by erickzhao** [comment]
After reading more on this... I think we have to refactor our components to simplify them and make them more testable.

**Comment by erickzhao** [comment]
@pierreTklein @krubenok lol

**Comment by krubenok** [comment]
>@pierreTklein @krubenok lol

@erickzhao L M A O
