### ISSUE TITLE
Improve file input styling

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/dashboard#141]
![image](https://user-images.githubusercontent.com/17463268/49692316-6ca64d80-fb25-11e8-8857-2d6ee3162ffa.png)

**Comment by erickzhao** [comment]
Can we shelve this then? @pierreTklein

**Comment by pierreTklein** [comment]
Depends on what design thinks we should do for the choose file btn-- @ailishm @krubenok @loreina

**Comment by loreina** [comment]
I can tackle this to match our other buttons for the next milestone

**Comment by erickzhao** [comment]
Alright. I updated the information accordingly, then.

**Comment by krubenok** [comment]
There also still seems to be an issue with the Asterix for required not appearing.
