### ISSUE TITLE
No mobile background on dashboard

### ISSUE THREAD

**Issue by loreina** [hackmcgill/dashboard#177]
The background on the login page stays on mobile but the background on the dashboard disappears once the screen gets too small.

![image](https://user-images.githubusercontent.com/23108291/49851137-16980b00-fdae-11e8-8f24-b951ab94b69c.png)
![image](https://user-images.githubusercontent.com/23108291/49851139-1861ce80-fdae-11e8-8abc-cdec5526648c.png)

Maybe just add the same conditions so there's no resizing to fit screen but also isn't blank?

**Comment by pierreTklein** [comment]
Are we ok with this? 
![localhost_1337_ iphone x](https://user-images.githubusercontent.com/17463268/49978362-19af0a80-ff18-11e8-9536-f22abd7f9664.png)

**Comment by erickzhao** [comment]
@pierreTklein LGTM
