### ISSUE TITLE
Tab selector box looks out of place

### ISSUE THREAD

**Issue by tbuffard** [hackmcgill/dashboard#191]
The box that appears around fields when their selected looks like it shouldn't be there. It also doesn't show up on the university name field.

![image](https://user-images.githubusercontent.com/13632759/49975108-583dc880-ff0a-11e8-94dc-e62d0a2a7b8c.png)

**Comment by erickzhao** [comment]
Example of custom focus styles for reference: https://css-tricks.com/focusing-on-focus-styles/

**Comment by krubenok** [comment]
Interesting Safari actually renders these really nice 🤔 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/2529120/49983382-643c8100-ff30-11e8-9bf0-e5927af52343.png">

**Comment by erickzhao** [comment]
Firefox does as well. I never noticed it while developing.

**Comment by loreina** [comment]
So it must be a chrome issue?

**Comment by erickzhao** [comment]
@loreina I wouldn't say it's an "issue" per se. It's just how the browser decided to style it. More of a design decision from Google?
