### ISSUE TITLE
Resize McHacks Logo

### ISSUE THREAD

**Issue by ailishm** [hackmcgill/dashboard#197]
![image](https://user-images.githubusercontent.com/43075123/49982272-bd54e680-ff29-11e8-9009-f554fb4ac943.png)
logo is too big (should match the size on the static site)

![image](https://user-images.githubusercontent.com/43075123/49982287-d52c6a80-ff29-11e8-9c47-aa399722a662.png)

**Comment by loreina** [comment]
done
