### ISSUE TITLE
Make search function not case sensitive

### ISSUE THREAD

**Issue by loreina** [hackmcgill/dashboard#453]
How it is right now:

![2019-02-09 18 42 48 1](https://user-images.githubusercontent.com/23108291/53192783-4b5de500-35dd-11e9-9ff2-c4daf04a6b3e.gif)

**Comment by erickzhao** [comment]
@loreina im a bit confused

<img width="434" alt="image" src="https://user-images.githubusercontent.com/16010076/56441287-941edb00-62ba-11e9-9849-dfbd4f7ac3f0.png">

why does this work then?

**Comment by loreina** [comment]
![image](https://user-images.githubusercontent.com/23108291/56461706-2c819200-6385-11e9-8d82-5c8e5f6be7ed.png)

![image](https://user-images.githubusercontent.com/23108291/56461708-33a8a000-6385-11e9-9f43-fed495220762.png)

I think it's for >5 chars, but not sure why 🤔
