### ISSUE TITLE
The application page is not working

### ISSUE THREAD

**Issue by Deerhound579** [hackmcgill/dashboard#753]
It seems like inputs are not detected properly.
![Capture](https://user-images.githubusercontent.com/43892874/71313002-9e244b00-2400-11ea-9d5b-7dc70cc8d9d1.PNG)

**Comment by pierreTklein** [comment]
Clear your chrome cache, we updated the application website!

**Comment by Deerhound579** [comment]
Cache cleared.
![cache](https://user-images.githubusercontent.com/43892874/71313146-c57c1780-2402-11ea-8a27-1238c8819002.PNG)
Still the same error message.
![Capture1](https://user-images.githubusercontent.com/43892874/71313147-c90f9e80-2402-11ea-87b3-8fc0a25c6ae8.PNG)

**Comment by pierreTklein** [comment]
Which browser are you using?

**Comment by Deerhound579** [comment]
I'm using Chrome.

**Comment by krubenok** [comment]
Have you cleared your DNS Cache recently?

https://www.siteground.com/kb/how_to_clear_the_local_dns_cache_in_windows/

In some weird cases we've seen it case the IP of old servers.

**Comment by Deerhound579** [comment]
![dns](https://user-images.githubusercontent.com/43892874/71314047-d3846500-240f-11ea-9eaf-caa1dbb2f180.PNG)
Clearing DNS cache didn't help, but I completed the application on Ubuntu 18.04 successfully. I was unable to view the updated site on my Windows machine even after the application. However, Incognito mode seems to fix the problem.

**Comment by pierreTklein** [comment]
I just want to confirm that when you cleared your cache, you went through these steps on Chrome:

<img width="690" alt="Screen Shot 2019-12-21 at 4 55 37 PM" src="https://user-images.githubusercontent.com/17463268/71314259-eb111d00-2412-11ea-940e-c6a5cc349501.png">

**Comment by Deerhound579** [comment]
That's the reason. Thank you for your help!
