### ISSUE TITLE
Cache busting issue

### ISSUE THREAD

**Issue by loreina** [hackmcgill/dashboard#820]
Seems like when the app builds, certain files aren't being bundled, like any files in `/features`. 

If we make any changes to an existing file, the file is still cached because it has the same name as the last release and browsers aren't recaching even if deployment is.

We had to make announcements and ask hackers to clear browser cache during application window. See https://github.com/hackmcgill/dashboard/issues/753

Would integrating [Webpack](https://webpack.js.org/) help with this?

**Comment by pierreTklein** [comment]
This seems like a really important unaddressed issue :(

**Comment by pierreTklein** [comment]
https://dev.to/flexdinesh/cache-busting-a-react-app-22lk

Haven't looked into the issue, but this webpage might be helpful.

**Comment by logan-r** [comment]
Yeah, this is going to be a massive issue rolling out bug fixes and changes if unaddressed. Will fix asap
