### ISSUE TITLE
Update look of login, create account and confirm email pages

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#822]
Look of login, create account and confirm email pages need to be update to match design spec. Functionality will stay the same.

Login page should look like so:
[![Image from Gyazo](https://i.gyazo.com/28e1facc8472c115e77b17dff09eb22c.png)](https://gyazo.com/28e1facc8472c115e77b17dff09eb22c)

Create account page should look like:
[![Image from Gyazo](https://i.gyazo.com/bc84ba74a0d49841ead6f83a6cfa2b92.png)](https://gyazo.com/bc84ba74a0d49841ead6f83a6cfa2b92)

Links in navbar should direct to appropriate section of `mchacks.ca` landing page.

Confirm email page should have no navbar visible on this:
[![Image from Gyazo](https://i.gyazo.com/728d3e25164a4e30f47cfc231d208673.png)](https://gyazo.com/728d3e25164a4e30f47cfc231d208673)

**Comment by loreina** [comment]
I think we should keep the navbar visible for confirm email page so there are page options to route to instead of having to close the tab and reopen.

**Comment by loreina** [comment]
I believe the spec didn't show the navbar b/c we were lazy 🙃
