### ISSUE TITLE
Reformat boolean variables to a specific naming structure

### ISSUE THREAD

**Issue by loreina** [hackmcgill/dashboard#844]
Short discussion on boolean state variables, and if we should use `loading` or `isLoading`

Seems like we collectively prefer `loading` but code base uses `is<BooleanVar>` throughout and might be a React convention?

Could be nice to look into and if we should reformat them to something we like internally

Ref: https://github.com/hackmcgill/dashboard/pull/842#discussion_r456830889

![image](https://user-images.githubusercontent.com/23108291/87865773-03b0c980-c947-11ea-8d10-f1313da051b5.png)

**Comment by pierreTklein** [comment]
The benefit of `is<bool name>` is that the type of the variable is immediately understood. Definitely worth looking up some naming conventions from large TS projects and using that as inspiration for this project’s naming conventions.
