### ISSUE TITLE
Add step pagination to application

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#867]
[![Image from Gyazo](https://i.gyazo.com/0885b872bf7598cf9ae88baff1f445b6.png)](https://gyazo.com/0885b872bf7598cf9ae88baff1f445b6)

Build a component that takes two props `pageNumber` and `totalPages` and renders the above bar. This bar does not need to have any iteraction yet. Embed this component in `ManageApplicationContainer` passing `pageNumber` in from `ManageApplicationContainer`'s state.

**Comment by jamesxu123** [comment]
What are the conditions for displaying a checkmark versus a purple number?

**Comment by logan-r** [comment]
Great questions!

First lets define some terms:

Props for this component:
* int `pageNumber` - the currently active page (in the example picture 2)
* int `totalPages` - the total number of pages (in the example picture 5)

We'll call each of the little step tabs *bubbles*, each having a step number (we'll call this `i` for now) from 1 to `totalPages`, and there are 4 possible states for each bubble: purple number, outlined number, purple checkmark & outlined checkmark.

This means each bubbles style is determined by two variables:
* bool isFilled - if true, then purple, else greyed outline
* bool isCheck - if true, the checkmark, else number

Make every page bubble up to and including the active page (so where `i` <= `activePage`) purple, others have greyed out border. Introduce new prop (alongside `pageNumber` and `totalPages`) called `lastCompletedPage`, any page up to and including that page **but not including the active page (where `i` == `pageNumber`)**, should have a checkmark, else have number.

For now, pass in ManageApplicationContainer's `pageNumber` state variable as the value of both the `pageNumber` and `lastCompletedPage` props, and create a new consts TOTAL_PAGES = 5, and pass that in for `totalPages` prop.


An example of how each bubble would be styled:

When activePage = 2, lastCompletedPage = 2, totalPages = 4:

Bubble Number (`i`) | isFilled | isCheck
---------|-----------|----------------
1 | True (as i <= activePage) | True (as i <= lastCompletedPage  and not i == activePage)
2 | True (as i <= activePage) | False (as i == activePage)
3 | False (as i > activePage) | False (as i > lastCompletedPage)
4 | False (as i > activePage) | False (as i > lastCompletedPage)

**Comment by pierreTklein** [comment]
1. Is it possible for a user to go back to a completed page and change their info?
2. If yes, is it possible for them to change the input on this page from a valid to an invalid state? 
3. If yes, how do we enforce the assumption that everything before the last completed page is still completed?

**Comment by logan-r** [comment]
For 1, yes it will be (not as part of this issue tho).

Clarification on navigation:
* User can navigate between pages of application via 3 ways: previous page button, next page button & through these pagination tabs
      * If they exit or change browser's current route, work just on current application page is lost
* Saving to database only occurs when you navigate between application pages
* When user tries to change application page, before api requests to update user's application object in db are sent, validation is performed. Only if validation succeeds is page changed carried out, otherwise invalid inputs are highlighted and users told they can't change application pages until they fix those.
       * they can still exit the browser window or navigate to a different url or what not, work just wouldn't be saved, only page changes within application are blocked,
* You can navigate freely to any page you have already completed and the page directly after the currently last completed page, but none beyond that
* When, and only when, you are on a previously competed page, "next page" button will ready "Save & Go To Next Page"

For 2, Yes, then they can't navigate to different application page until they fix it though

For 3, you won't be allowed to navigate forwards beyond the current last page to any page except the one right after. Further, if you go back to a page before last completed page, that page won't be updated until it passes validation.

**Comment by jamesxu123** [comment]
Thank you for everyone's comments. Couple of questions:

1. Is there a mobile design or should this just be hidden?
2. ManageApplicationContainer currently has a max-width of 500px, is it OK if the pagination component looks a little squashed?

As a workaround for (2), I used this for the width instead of the 160px suggested on Figma: `${(500 - 5 * 24) / (this.props.totalPages - 1)}px`.

------
Mobile: 
<img width="247" alt="mobile" src="https://user-images.githubusercontent.com/36768789/95907659-e040c380-0d69-11eb-9ef7-09956e024ff2.png">

Squashed:
<img width="702" alt="squashed" src="https://user-images.githubusercontent.com/36768789/95907669-e59e0e00-0d69-11eb-9566-abaf771990b8.png">

Work Around:
<img width="702" alt="workAround" src="https://user-images.githubusercontent.com/36768789/95907689-ed5db280-0d69-11eb-9bd8-d1b8584e7470.png">

**Comment by logan-r** [comment]
For 1, yeah, this bar will be hidden on mobile (don't worry about the implementation of that right now tho, we'll handle that with a bigger PR for making application form responsive). 

For 2, yeah the width should scale with number of pages.

**Comment by pierreTklein** [comment]
Instead of hard coding 500px twice, is it possible to have one reference to the max width? Otherwise nbd

**Comment by jamesxu123** [comment]
I removed the dynamic bar length and just made each bar 160px in a new commit. It seems that the new design on Figma won't have such a small max width so I didn't want to reference anything that will be removed soon.

**Comment by pierreTklein** [comment]
@jamesxu123 I noticed that the circles are still squashed: 
![image](https://user-images.githubusercontent.com/17463268/96070525-634b4200-0e6e-11eb-9851-8613ef24635c.png) 

Is this expected?

**Comment by jamesxu123** [comment]
@pierreTklein Yeah, this is expected. The reason it is squashed is because of the 500px max width in the application container. This max width should be removed in the new design that is yet to be implemented:
![image](https://user-images.githubusercontent.com/36768789/96072380-339e3900-0e72-11eb-8e4e-7830799f376f.png)
