### ISSUE TITLE
Implement new design for main dashboard page

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#884]
Main dashboard pages should be updated so it follows the following format from the figma:

(Different art per state pending, also need to figure out way to include link to edit profile as that's not specified in design)

![image](https://user-images.githubusercontent.com/3229837/97501578-e200ae80-1947-11eb-8ed6-b647e01a5e1a.png)
![image](https://user-images.githubusercontent.com/3229837/97501604-eb8a1680-1947-11eb-9e95-a5a72a399110.png)

**Comment by pierreTklein** [comment]
What about the existing nav items on the upper right?

**Comment by logan-r** [comment]
Think I'll end up dropping the social media icons for nav items - tried them side-by-side and it's too crowded
![image](https://user-images.githubusercontent.com/3229837/97505955-40ca2600-1950-11eb-9085-15a283100960.png)

Going to try playing around with the design - could maybe get rid of home, and move application and profile to buttons below the text blob depending on state, but feels like that'll end up with too many buttons especially since we need to support teams and travel. Social media buttons are good but not essential.
