### ISSUE TITLE
Implement remote hackathon mode

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#887]
Implement a constant Boolean IS_REMOTE_HACKATHON.

When true:
* hides travel field from application (setting all travel values to 0 in post/put requests)
* hides tshirt size field from application (setting all tshirt size values to "M" in post/put requests)
* hides travel tab from navbar
* hides dietary restrictions field from account creation/editing (setting dietary restrictions to ["Unknown"] for all account creations, and using existing dietary restrictions value for all account updates)

**Comment by pierreTklein** [comment]
ultimately this will be wired into the settings schema

**Comment by jamesxu123** [comment]
Should I put this in the consts file or add to the ISettings interface?

**Comment by pierreTklein** [comment]
This should use the field exposed by https://github.com/hackmcgill/hackerAPI/pull/675

**Comment by pierreTklein** [comment]
In other words, update ISettings to have the `isRemote` Boolean field, and then use that field for all frontend display logic

**Comment by jamesxu123** [comment]
Got it, thank you!
