### ISSUE TITLE
Make team page work

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#893]
Right now /team page doesn't leave loading state. 

Not sure if team api was fully completed. Investigate and see what needs to be fixed/implemented

Design doc:
https://docs.google.com/document/d/1H1NjxuhJljVcRkqAmnG4lOlKTuWq5GEmEPO-MXtLE0E/edit

**Comment by pierreTklein** [comment]
Team API should have been completed. I don't remember the state machine tho. Do you know the HTTP error that is sent by the API when you load the team page?

**Comment by logan-r** [comment]
It looks like API is never contacted. `getTeam` method is never called on `TeamPage` so api isn't contacted

**Comment by logan-r** [comment]
The useEffect in TeamPage is returning a function instead of calling it and there seems to be a conflict between setting state in use effect and Helmet: https://github.com/nfl/react-helmet/issues/373

**Comment by logan-r** [comment]
There seems to be an underlying issue with endless state update loop that react-helmet is just indicative of. Investigating now: https://github.com/hackmcgill/dashboard/pull/897

**Comment by logan-r** [comment]
Split into #896 and #898
