### ISSUE TITLE
Back button on application page not working

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/dashboard#919]
Clicking 'back' on the second application page does not do anything (including bring me to the first page).

**Comment by pierreTklein** [comment]
@logan-r FYI

**Comment by logan-r** [comment]
Thanks for the heads up! 👍

**Comment by logan-r** [comment]
#921 broke next page button on first application page, meaning user couldn't fill out application at all :(

**Comment by jamesxu123** [comment]
Oh yikes sorry about that! I'll take a look

**Comment by jamesxu123** [comment]
Hey, I'm testing my fix again but I can't seem to replicate the problem.

**Comment by pierreTklein** [comment]
Might be browser-dependent. @logan-r can you provide system requirements & repro steps?

**Comment by logan-r** [comment]
It's Chromium issue looks like, works fine in Firefox

Adding `onReset={fp.handleReset}` to 
```
const renderPortfolioFormik = (fp: FormikProps<any>) => {
    return (
      <Form
        onKeyDown={onKeyDown}
        onSubmit={fp.handleSubmit}
        onReset={fp.handleReset}
      >
```
fixes back button issue on page 2, but breaks next button on page 1 for chromium browsers (testing on windows 10 )

Reset function is being called when user moves to page 2 even though they didn't click back button, causing them to go back to page 1

**Comment by jamesxu123** [comment]
For some reason adding a disabled back button solves the issue.
![image](https://user-images.githubusercontent.com/36768789/100483308-720c5200-30c6-11eb-8dda-dd5211530fbb.png)
If this looks alright maybe we can consider it as a workaround?

**Comment by logan-r** [comment]
Oh wow, this is a strange bug. Does the button still work in disabled state, like are we guaranteed that browser will always trigger a onReset event for a disabled reset button?

We should probably figure out what root problem is though. Having reset events firing when they shouldn't be is quite worrying and something we need to get to the bottom of.

**Comment by jamesxu123** [comment]
Yeah it's quite strange. From some quick testing on FF and Edge Chromium it does seem to work by stopping onReset from firing, though I'm not entirely sure why that works.

**Comment by logan-r** [comment]
If you remove the reset button from the second page, but leave the reset event handler attached to the second page's form does it still call onReset handler right after moving from first to second page?

**Comment by jamesxu123** [comment]
No, it doesn't anymore.

**Comment by jamesxu123** [comment]
Another potential solution that doesn't change the visual design is to keep the disabled button in `renderEducationFormik()` but just set it to `display: none;`.
![image](https://user-images.githubusercontent.com/36768789/100524482-7dbf4d80-3186-11eb-87ac-8cbf0d529823.png)
