### ISSUE TITLE
Single view hacker page is broken

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/dashboard#933]
(E.g. Logan's page on prod: https://app.mchacks.ca/application/view/5fc0725713b3e4001714971f) 

It displays "loading", and then the page goes blank. This occurs when I am on mobile (haven't tried on other platforms).

**Comment by logan-r** [comment]
Can replicate on laptop

**Comment by jamesxu123** [comment]
After some debugging with both my test and production database it seems the issue only pops up if you use the production build and not the development build. Could someone perhaps confirm this?

**Comment by logan-r** [comment]
Isolated this bug to the `this.setState({ isAdmin });` line in `SingleHackerView` causing the `Maximum call stack size exceeded` error

```
public componentDidMount() {
    const isAdmin = true;
    this.setState({ isAdmin });
    this.submit = this.submit.bind(this);
  }
```
