### ISSUE TITLE
Positioning issues with nav menu on mobile

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/dashboard#936]
Nav menu has positioning issues when the page is scrolled down. See https://hackboard8.slack.com/files/U9ZBHJDBR/F01FNC03YHK/image_from_ios.mp4

**Comment by allennatang** [comment]
The nav bar on the top of the dashboard does not change when scrolled down. I can't access this image, so no way to know what he was talking about.

**Comment by allennatang** [comment]
> The nav bar on the top of the dashboard does not change when scrolled down. I can't access this image, so no way to know what he was talking about.

Need to double check
