### ISSUE TITLE
Create stats dashboard page

### ISSUE THREAD

**Issue by jamesxu123** [hackmcgill/dashboard#950]
Implement a staff dashboard to show application statistics and leverage existing API

- Enable timestamps for each application submission (I think Logan mentioned this being a one-liner)
- Add any additional stats we want to the API
- Build front-end charts and interface and integrate with dashboard (i.e charts.js or something similar)

**Comment by pierreTklein** [comment]
There's a 2+ year old PR which displayed some data. Not sure if it's worth going through that when working on this issue
